import React, { useState, useEffect, useCallback } from 'react';
import { 
  Bell, AlertTriangle, CheckCircle2, Clock, TrendingDown, 
  Plus, Settings, FileText, Truck, Send, X, Check, 
  ArrowRight, Package, Building2, DollarSign, BarChart3,
  Filter, RefreshCw, ChevronDown, ChevronUp, MoreVertical,
  Trash2, Edit2, Eye, WhatsApp, Mail, Printer,
  AlertCircle, Info, Shield, Save
} from 'lucide-react';

const API_URL = process.env.REACT_APP_API_URL || '/api';
const getAuthToken = () => localStorage.getItem('token');

const headers = () => ({
  'Content-Type': 'application/json',
  'Authorization': `Bearer ${getAuthToken()}`
});

// Demo data for development
const demoRawMaterials = [
  { _id: 'rm1', name: 'Yellow Corn (Maize)', code: 'RM-CORN-001', category: 'grain', quantity: 2500, unit: 'kg', costPerUnit: 800, minimumStock: 5000, reorderLevel: 8000, reorderQuantity: 10000, autoPOEnabled: true, preferredSupplier: 'ABC Feeds Ltd', status: 'active' },
  { _id: 'rm2', name: 'Soybean Meal', code: 'RM-SBM-001', category: 'protein', quantity: 1500, unit: 'kg', costPerUnit: 1200, minimumStock: 3000, reorderLevel: 5000, reorderQuantity: 6000, autoPOEnabled: true, preferredSupplier: 'ABC Feeds Ltd', status: 'active' },
  { _id: 'rm3', name: 'Wheat Bran', code: 'RM-WHB-001', category: 'fiber', quantity: 800, unit: 'kg', costPerUnit: 700, minimumStock: 2000, reorderLevel: 3500, reorderQuantity: 4000, autoPOEnabled: false, preferredSupplier: 'Agro Supplies Inc', status: 'active' },
  { _id: 'rm4', name: 'Fish Meal', code: 'RM-FISH-001', category: 'protein', quantity: 500, unit: 'kg', costPerUnit: 2500, minimumStock: 1000, reorderLevel: 2000, reorderQuantity: 3000, autoPOEnabled: true, preferredSupplier: 'Agro Supplies Inc', status: 'active' },
  { _id: 'rm5', name: 'Palm Oil', code: 'RM-OIL-001', category: 'oil', quantity: 3500, unit: 'kg', costPerUnit: 2200, minimumStock: 800, reorderLevel: 1500, reorderQuantity: 2000, autoPOEnabled: true, preferredSupplier: 'Agro Supplies Inc', status: 'active' },
  { _id: 'rm6', name: 'Limestone Powder', code: 'RM-LST-001', category: 'mineral', quantity: 4500, unit: 'kg', costPerUnit: 400, minimumStock: 900, reorderLevel: 1500, reorderQuantity: 2000, autoPOEnabled: true, preferredSupplier: '', status: 'active' }
];

const demoSuppliers = [
  { _id: '1', name: 'ABC Feeds Ltd', code: 'SUP-001', contactPerson: 'John Smith', phone: '+255 712 345 678', whatsapp: '+255 712 345 678', email: 'john@abcfeeds.com', materials: ['Yellow Corn (Maize)', 'Soybean Meal', 'Wheat Bran'], rating: 4.5, onTimeDelivery: 95, status: 'active' },
  { _id: '2', name: 'Agro Supplies Inc', code: 'SUP-002', contactPerson: 'Sarah Johnson', phone: '+255 713 456 789', whatsapp: '+255 713 456 789', email: 'sarah@agrosupplies.com', materials: ['Wheat Bran', 'Fish Meal', 'Palm Oil'], rating: 4.0, onTimeDelivery: 88, status: 'active' },
  { _id: '3', name: 'Tanzania Grains Co', code: 'SUP-003', contactPerson: 'Michael Brown', phone: '+255 714 567 890', whatsapp: '+255 714 567 890', email: 'michael@tzgrains.com', materials: ['Yellow Corn (Maize)'], rating: 3.5, onTimeDelivery: 75, status: 'active' }
];

const demoPurchaseRequisitions = [
  { _id: 'pr1', prNumber: 'PR-2024-001', material: { _id: 'rm1', name: 'Yellow Corn (Maize)', code: 'RM-CORN-001', currentStock: 2500, minimumStock: 5000, unit: 'kg' }, quantity: 10000, unitCost: 800, totalCost: 8000000, suggestedSuppliers: ['ABC Feeds Ltd', 'Tanzania Grains Co'], preferredSupplier: { _id: '1', name: 'ABC Feeds Ltd' }, status: 'pending', priority: 'high', createdAt: '2024-01-15T10:00:00Z', createdBy: 'System', notes: 'Auto-generated: Stock below minimum threshold', isAutoGenerated: true },
  { _id: 'pr2', prNumber: 'PR-2024-002', material: { _id: 'rm2', name: 'Soybean Meal', code: 'RM-SBM-001', currentStock: 1500, minimumStock: 3000, unit: 'kg' }, quantity: 6000, unitCost: 1200, totalCost: 7200000, suggestedSuppliers: ['ABC Feeds Ltd'], preferredSupplier: { _id: '1', name: 'ABC Feeds Ltd' }, status: 'pending', priority: 'high', createdAt: '2024-01-15T10:05:00Z', createdBy: 'System', notes: 'Auto-generated: Stock below minimum threshold', isAutoGenerated: true }
];

const demoPurchaseOrders = [
  { _id: 'po1', poNumber: 'PO-2024-001', prNumber: 'PR-2024-001', supplier: { _id: '1', name: 'ABC Feeds Ltd', whatsapp: '+255 712 345 678', email: 'john@abcfeeds.com' }, items: [{ material: 'Yellow Corn (Maize)', quantity: 10000, unit: 'kg', unitPrice: 800, total: 8000000 }], subtotal: 8000000, vat: 1120000, total: 9120000, deliveryDate: '2024-01-22', status: 'approved', createdAt: '2024-01-15T11:00:00Z', approvedBy: 'Inventory Manager', approvedAt: '2024-01-15T11:30:00Z', notes: 'Approved for production needs' }
];

const demoNotifications = [
  { _id: 'n1', type: 'alert', title: 'Low Stock Alert', message: 'Yellow Corn (Maize) stock is below minimum level (2,500 kg remaining)', materialId: 'rm1', priority: 'high', read: false, createdAt: '2024-01-15T09:00:00Z' },
  { _id: 'n2', type: 'alert', title: 'Low Stock Alert', message: 'Soybean Meal stock is below minimum level (1,500 kg remaining)', materialId: 'rm2', priority: 'high', read: false, createdAt: '2024-01-15T09:05:00Z' },
  { _id: 'n3', type: 'pr', title: 'New Purchase Requisition', message: 'Auto-generated PR-2024-001 requires approval', prId: 'pr1', priority: 'medium', read: false, createdAt: '2024-01-15T10:00:00Z' },
  { _id: 'n4', type: 'pr', title: 'New Purchase Requisition', message: 'Auto-generated PR-2024-002 requires approval', prId: 'pr2', priority: 'medium', read: false, createdAt: '2024-01-15T10:05:00Z' }
];

// Status Badge Component
const StatusBadge = ({ status, type }) => {
  const getStyles = () => {
    if (type === 'pr' || type === 'po') {
      switch (status) {
        case 'draft':
        case 'pending':
          return { bg: '#fef3c7', color: '#92400e' };
        case 'pending_approval':
          return { bg: '#dbeafe', color: '#1e40af' };
        case 'approved':
          return { bg: '#dcfce7', color: '#166534' };
        case 'rejected':
          return { bg: '#fee2e2', color: '#991b1b' };
        case 'ordered':
          return { bg: '#e0e7ff', color: '#3730a3' };
        case 'received':
          return { bg: '#d1fae5', color: '#065f46' };
        default:
          return { bg: '#f3f4f6', color: '#6b7280' };
      }
    } else if (type === 'notification') {
      switch (status) {
        case 'high':
          return { bg: '#fee2e2', color: '#991b1b' };
        case 'medium':
          return { bg: '#fef3c7', color: '#92400e' };
        case 'low':
          return { bg: '#dbeafe', color: '#1e40af' };
        default:
          return { bg: '#f3f4f6', color: '#6b7280' };
      }
    }
  };
  
  const styles = getStyles();
  
  return (
    <span style={{
      padding: '4px 12px',
      borderRadius: '12px',
      fontSize: '12px',
      fontWeight: '500',
      textTransform: 'capitalize',
      backgroundColor: styles.bg,
      color: styles.color,
      display: 'inline-flex',
      alignItems: 'center',
      gap: '4px'
    }}>
      {status.replace('_', ' ')}
    </span>
  );
};

// Priority Badge Component
const PriorityBadge = ({ priority }) => {
  const getColor = () => {
    switch (priority) {
      case 'high': return { bg: '#fee2e2', color: '#991b1b', icon: AlertTriangle };
      case 'medium': return { bg: '#fef3c7', color: '#92400e', icon: Info };
      case 'low': return { bg: '#dbeafe', color: '#1e40af', icon: Info };
      default: return { bg: '#f3f4f6', color: '#6b7280', icon: Info };
    }
  };
  
  const { bg, color, icon: Icon } = getColor();
  
  return (
    <span style={{
      padding: '4px 8px',
      borderRadius: '8px',
      fontSize: '11px',
      fontWeight: '600',
      textTransform: 'uppercase',
      backgroundColor: bg,
      color: color,
      display: 'inline-flex',
      alignItems: 'center',
      gap: '4px'
    }}>
      <Icon size={12} />
      {priority}
    </span>
  );
};

// Low Stock Alert Card
const LowStockAlertCard = ({ material, onCreatePR, onViewMaterial }) => {
  const stockPercentage = (material.quantity / material.minimumStock) * 100;
  const isCritical = material.quantity <= material.minimumStock * 0.5;
  
  return (
    <div style={{
      padding: '16px',
      borderRadius: '8px',
      border: '1px solid',
      borderColor: isCritical ? '#fecaca' : '#fed7aa',
      backgroundColor: isCritical ? '#fef2f2' : '#fffbeb',
      marginBottom: '12px'
    }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '12px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <AlertTriangle size={20} color={isCritical ? '#dc2626' : '#f59e0b'} />
          <div>
            <div style={{ fontWeight: 600, fontSize: '14px' }}>{material.name}</div>
            <div style={{ fontSize: '12px', color: '#6b7280' }}>{material.code}</div>
          </div>
        </div>
        <PriorityBadge priority={isCritical ? 'high' : 'medium'} />
      </div>
      
      <div style={{ marginBottom: '12px' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '4px' }}>
          <span style={{ fontSize: '12px', color: '#6b7280' }}>Stock Level</span>
          <span style={{ fontSize: '12px', fontWeight: 500 }}>
            {material.quantity.toLocaleString()} / {material.minimumStock.toLocaleString()} {material.unit}
          </span>
        </div>
        <div style={{ 
          height: '6px', 
          backgroundColor: '#e5e7eb', 
          borderRadius: '3px',
          overflow: 'hidden'
        }}>
          <div style={{
            height: '100%',
            width: `${Math.min(stockPercentage, 100)}%`,
            backgroundColor: isCritical ? '#dc2626' : '#f59e0b',
            borderRadius: '3px',
            transition: 'width 0.3s ease'
          }} />
        </div>
        <div style={{ fontSize: '11px', color: '#ef4444', marginTop: '4px' }}>
          {stockPercentage.toFixed(0)}% of minimum stock remaining
        </div>
      </div>
      
      <div style={{ display: 'flex', gap: '8px' }}>
        {material.autoPOEnabled ? (
          <button 
            className="btn btn-sm btn-primary"
            onClick={() => onCreatePR(material)}
          >
            <Plus size={14} style={{ marginRight: '4px', display: 'inline' }} />
            Auto-Create PR
          </button>
        ) : (
          <button 
            className="btn btn-sm btn-secondary"
            onClick={() => onCreatePR(material)}
          >
            <Plus size={14} style={{ marginRight: '4px', display: 'inline' }} />
            Create PR
          </button>
        )}
        <button 
          className="btn btn-sm"
          onClick={() => onViewMaterial(material)}
        >
          <Eye size={14} style={{ marginRight: '4px', display: 'inline' }} />
          Details
        </button>
      </div>
    </div>
  );
};

// Purchase Requisition Card
const PurchaseRequisitionCard = ({ pr, onApprove, onReject, onView, suppliers }) => {
  const [showActions, setShowActions] = useState(false);
  
  return (
    <div style={{
      padding: '16px',
      borderRadius: '8px',
      border: '1px solid #e5e7eb',
      backgroundColor: 'white',
      marginBottom: '12px'
    }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '12px' }}>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '4px' }}>
            <FileText size={18} style={{ color: '#3b82f6' }} />
            <span style={{ fontWeight: 600 }}>{pr.prNumber}</span>
            {pr.isAutoGenerated && (
              <span style={{
                padding: '2px 6px',
                borderRadius: '4px',
                fontSize: '10px',
                backgroundColor: '#e0e7ff',
                color: '#3730a3'
              }}>
                Auto
              </span>
            )}
          </div>
          <div style={{ fontSize: '12px', color: '#6b7280' }}>
            Created {new Date(pr.createdAt).toLocaleString()} by {pr.createdBy}
          </div>
        </div>
        <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: '4px' }}>
          <StatusBadge status={pr.status} type="pr" />
          <PriorityBadge priority={pr.priority} />
        </div>
      </div>
      
      <div style={{ marginBottom: '12px' }}>
        <div style={{ fontSize: '14px', fontWeight: 500, marginBottom: '4px' }}>
          <Package size={14} style={{ display: 'inline', marginRight: '4px', color: '#6b7280' }} />
          {pr.material.name}
        </div>
        <div style={{ fontSize: '12px', color: '#6b7280', marginBottom: '8px' }}>
          Current Stock: {pr.material.currentStock.toLocaleString()} {pr.material.unit} 
          (Min: {pr.material.minimumStock.toLocaleString()} {pr.material.unit})
        </div>
        
        <div style={{ 
          display: 'grid', 
          gridTemplateColumns: 'repeat(3, 1fr)', 
          gap: '8px',
          padding: '12px',
          backgroundColor: '#f9fafb',
          borderRadius: '6px'
        }}>
          <div>
            <div style={{ fontSize: '11px', color: '#6b7280' }}>Quantity</div>
            <div style={{ fontWeight: 600 }}>{pr.quantity.toLocaleString()} {pr.material.unit}</div>
          </div>
          <div>
            <div style={{ fontSize: '11px', color: '#6b7280' }}>Unit Cost</div>
            <div style={{ fontWeight: 600 }}>EGP {pr.unitCost.toLocaleString()}</div>
          </div>
          <div>
            <div style={{ fontSize: '11px', color: '#6b7280' }}>Total Cost</div>
            <div style={{ fontWeight: 600, color: '#22c55e' }}>EGP {pr.totalCost.toLocaleString()}</div>
          </div>
        </div>
      </div>
      
      <div style={{ marginBottom: '12px' }}>
        <div style={{ fontSize: '12px', color: '#6b7280', marginBottom: '4px' }}>Suggested Suppliers:</div>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: '4px' }}>
          {pr.suggestedSuppliers.map((supplier, idx) => (
            <span key={idx} style={{
              padding: '4px 8px',
              borderRadius: '4px',
              fontSize: '11px',
              backgroundColor: supplier === pr.preferredSupplier?.name ? '#dcfce7' : '#f3f4f6',
              color: supplier === pr.preferredSupplier?.name ? '#166534' : '#6b7280'
            }}>
              {supplier === pr.preferredSupplier?.name && <CheckCircle2 size={10} style={{ display: 'inline', marginRight: '2px' }} />}
              {supplier}
            </span>
          ))}
        </div>
      </div>
      
      {pr.notes && (
        <div style={{ 
          padding: '8px 12px', 
          backgroundColor: '#f3f4f6', 
          borderRadius: '4px',
          fontSize: '12px',
          color: '#6b7280',
          marginBottom: '12px'
        }}>
          <Info size={12} style={{ display: 'inline', marginRight: '4px' }} />
          {pr.notes}
        </div>
      )}
      
      <div style={{ display: 'flex', gap: '8px' }}>
        {pr.status === 'pending' && (
          <>
            <button 
              className="btn btn-sm btn-success"
              onClick={() => setShowActions(true)}
            >
              <Check size={14} style={{ marginRight: '4px', display: 'inline' }} />
              Review & Approve
            </button>
            <button 
              className="btn btn-sm btn-danger"
              onClick={() => onReject(pr)}
            >
              <X size={14} style={{ marginRight: '4px', display: 'inline' }} />
              Reject
            </button>
          </>
        )}
        <button 
          className="btn btn-sm"
          onClick={() => onView(pr)}
          style={{ marginLeft: 'auto' }}
        >
          <Eye size={14} style={{ marginRight: '4px', display: 'inline' }} />
          View Details
        </button>
      </div>
      
      {/* Approval Modal */}
      {showActions && (
        <PRApprovalModal
          pr={pr}
          suppliers={suppliers}
          onClose={() => setShowActions(false)}
          onApprove={onApprove}
        />
      )}
    </div>
  );
};

// PR Approval Modal
const PRApprovalModal = ({ pr, suppliers, onClose, onApprove }) => {
  const [formData, setFormData] = useState({
    quantity: pr.quantity,
    supplierId: pr.preferredSupplier?._id || '',
    deliveryDate: '',
    notes: ''
  });
  const [isSubmitting, setIsSubmitting] = useState(false);
  
  const selectedSupplier = suppliers.find(s => s._id === formData.supplierId);
  const total = formData.quantity * pr.unitCost;
  
  const handleSubmit = async (e) => {
    e.preventDefault();
    setIsSubmitting(true);
    
    await onApprove({
      ...pr,
      quantity: parseFloat(formData.quantity),
      supplierId: formData.supplierId,
      supplier: selectedSupplier,
      deliveryDate: formData.deliveryDate,
      notes: formData.notes,
      totalCost: total
    });
    
    setIsSubmitting(false);
    onClose();
  };
  
  return (
    <div className="modal-overlay" onClick={(e) => e.target === e.currentTarget && onClose()}>
      <div className="modal" style={{ maxWidth: '500px' }}>
        <div className="modal-header">
          <h3 className="modal-title">Approve PR: {pr.prNumber}</h3>
          <button className="modal-close" onClick={onClose}>
            <X size={20} />
          </button>
        </div>
        
        <form onSubmit={handleSubmit}>
          <div className="modal-body">
            <div style={{ padding: '12px', backgroundColor: '#e3f2fd', borderRadius: '6px', marginBottom: '16px' }}>
              <div style={{ fontSize: '14px', fontWeight: 500 }}>
                <Package size={14} style={{ display: 'inline', marginRight: '4px' }} />
                {pr.material.name}
              </div>
              <div style={{ fontSize: '12px', color: '#6b7280', marginTop: '4px' }}>
                Recommended: {pr.quantity.toLocaleString()} {pr.material.unit}
              </div>
            </div>
            
            <div className="form-group">
              <label className="form-label">Quantity *</label>
              <input
                type="number"
                className="form-input"
                value={formData.quantity}
                onChange={(e) => setFormData({ ...formData, quantity: e.target.value })}
                min="1"
                step="1"
                required
              />
            </div>

            <div className="form-group">
              <label className="form-label">Select Supplier *</label>
              <select
                className="form-select"
                value={formData.supplierId}
                onChange={(e) => setFormData({ ...formData, supplierId: e.target.value })}
                required
              >
                <option value="">Select a supplier</option>
                {suppliers
                  .filter(s => pr.suggestedSuppliers.includes(s.name))
                  .map(supplier => (
                    <option key={supplier._id} value={supplier._id}>
                      {supplier.name} (Rating: {supplier.rating})
                    </option>
                  ))}
              </select>
            </div>
            
            {selectedSupplier && (
              <div style={{ padding: '12px', backgroundColor: '#f9fafb', borderRadius: '6px', marginBottom: '16px' }}>
                <div style={{ fontSize: '12px', color: '#6b7280', marginBottom: '4px' }}>Selected Supplier:</div>
                <div style={{ fontWeight: 500 }}>{selectedSupplier.name}</div>
                <div style={{ fontSize: '12px', color: '#6b7280' }}>
                  Contact: {selectedSupplier.contactPerson} • {selectedSupplier.phone}
                </div>
              </div>
            )}
            
            <div className="form-group">
              <label className="form-label">Required Delivery Date *</label>
              <input
                type="date"
                className="form-input"
                value={formData.deliveryDate}
                onChange={(e) => setFormData({ ...formData, deliveryDate: e.target.value })}
                min={new Date().toISOString().split('T')[0]}
                required
              />
            </div>
            
            <div style={{ 
              padding: '12px', 
              backgroundColor: '#f9fafb', 
              borderRadius: '6px',
              marginBottom: '16px'
            }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '4px' }}>
                <span>Subtotal:</span>
                <span>EGP {total.toLocaleString()}</span>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '4px' }}>
                <span>VAT (14%):</span>
                <span>EGP {(total * 0.14).toLocaleString()}</span>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontWeight: 'bold', fontSize: '16px', color: '#22c55e' }}>
                <span>Total:</span>
                <span>EGP {(total * 1.14).toLocaleString()}</span>
              </div>
            </div>
            
            <div className="form-group">
              <label className="form-label">Approval Notes</label>
              <textarea
                className="form-textarea"
                value={formData.notes}
                onChange={(e) => setFormData({ ...formData, notes: e.target.value })}
                placeholder="Add any notes or special instructions..."
                rows="3"
              />
            </div>
          </div>
          
          <div className="modal-footer">
            <button type="button" className="btn btn-secondary" onClick={onClose}>
              Cancel
            </button>
            <button 
              type="submit" 
              className="btn btn-success"
              disabled={isSubmitting || !formData.supplierId}
            >
              {isSubmitting ? (
                <>
                  <RefreshCw size={16} style={{ animation: 'spin 1s linear infinite', marginRight: '8px', display: 'inline' }} />
                  Processing...
                </>
              ) : (
                <>
                  <Check size={16} style={{ marginRight: '8px', display: 'inline' }} />
                  Approve & Create PO
                </>
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

// Material Settings Modal
const MaterialSettingsModal = ({ material, suppliers, onClose, onSave }) => {
  const [formData, setFormData] = useState({
    autoPOEnabled: material?.autoPOEnabled ?? false,
    minimumStock: material?.minimumStock || 0,
    reorderLevel: material?.reorderLevel || 0,
    reorderQuantity: material?.reorderQuantity || 0,
    preferredSupplier: material?.preferredSupplier || ''
  });
  
  const handleSubmit = (e) => {
    e.preventDefault();
    onSave({
      ...material,
      ...formData
    });
    onClose();
  };
  
  return (
    <div className="modal-overlay" onClick={(e) => e.target === e.currentTarget && onClose()}>
      <div className="modal" style={{ maxWidth: '500px' }}>
        <div className="modal-header">
          <h3 className="modal-title">
            <Settings size={18} style={{ display: 'inline', marginRight: '8px' }} />
            Auto-PO Settings: {material?.name}
          </h3>
          <button className="modal-close" onClick={onClose}>
            <X size={20} />
          </button>
        </div>
        
        <form onSubmit={handleSubmit}>
          <div className="modal-body">
            <div style={{ padding: '12px', backgroundColor: '#f9fafb', borderRadius: '6px', marginBottom: '16px' }}>
              <div style={{ fontSize: '12px', color: '#6b7280' }}>Current Stock:</div>
              <div style={{ fontSize: '20px', fontWeight: 'bold', color: '#3b82f6' }}>
                {material?.quantity?.toLocaleString()} {material?.unit}
              </div>
            </div>
            
            <div className="form-group">
              <label style={{ display: 'flex', alignItems: 'center', gap: '8px', cursor: 'pointer' }}>
                <input
                  type="checkbox"
                  checked={formData.autoPOEnabled}
                  onChange={(e) => setFormData({ ...formData, autoPOEnabled: e.target.checked })}
                />
                <span>Enable Auto-PO for this material</span>
              </label>
              <small className="form-help">
                When enabled, the system will automatically create a Purchase Requisition when stock falls below the minimum threshold.
              </small>
            </div>
            
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
              <div className="form-group">
                <label className="form-label">Minimum Stock Level *</label>
                <input
                  type="number"
                  className="form-input"
                  value={formData.minimumStock}
                  onChange={(e) => setFormData({ ...formData, minimumStock: parseFloat(e.target.value) || 0 })}
                  min="0"
                  step="1"
                  required
                />
                <small className="form-help">Alert when stock falls below this level</small>
              </div>
              
              <div className="form-group">
                <label className="form-label">Reorder Level *</label>
                <input
                  type="number"
                  className="form-input"
                  value={formData.reorderLevel}
                  onChange={(e) => setFormData({ ...formData, reorderLevel: parseFloat(e.target.value) || 0 })}
                  min="0"
                  step="1"
                  required
                />
                <small className="form-help">Trigger PR when stock falls below this</small>
              </div>
            </div>
            
            <div className="form-group">
              <label className="form-label">Reorder Quantity *</label>
              <input
                type="number"
                className="form-input"
                value={formData.reorderQuantity}
                onChange={(e) => setFormData({ ...formData, reorderQuantity: parseFloat(e.target.value) || 0 })}
                min="0"
                step="1"
                required
              />
              <small className="form-help">Default quantity to order when creating PR</small>
            </div>
            
            <div className="form-group">
              <label className="form-label">Preferred Supplier</label>
              <select
                className="form-select"
                value={formData.preferredSupplier}
                onChange={(e) => setFormData({ ...formData, preferredSupplier: e.target.value })}
              >
                <option value="">No preferred supplier</option>
                {suppliers.map(supplier => (
                  <option key={supplier._id} value={supplier._id}>
                    {supplier.name}
                  </option>
                ))}
              </select>
              <small className="form-help">This supplier will be suggested first in auto-generated PRs</small>
            </div>
          </div>
          
          <div className="modal-footer">
            <button type="button" className="btn btn-secondary" onClick={onClose}>
              Cancel
            </button>
            <button type="submit" className="btn btn-success">
              <Save size={16} style={{ marginRight: '8px', display: 'inline' }} />
              Save Settings
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

// Create PR Modal
const CreatePRModal = ({ material, suppliers, onClose, onSubmit }) => {
  const [formData, setFormData] = useState({
    quantity: material?.reorderQuantity || material?.minimumStock || 1000,
    supplierId: material?.preferredSupplier || '',
    priority: 'medium',
    notes: ''
  });
  const [isSubmitting, setIsSubmitting] = useState(false);
  
  const selectedSupplier = suppliers.find(s => s._id === formData.supplierId);
  const unitCost = material?.costPerUnit || 0;
  const totalCost = formData.quantity * unitCost;
  
  const handleSubmit = async (e) => {
    e.preventDefault();
    setIsSubmitting(true);
    
    await onSubmit({
      materialId: material._id,
      materialName: material.name,
      materialCode: material.code,
      currentStock: material.quantity,
      minimumStock: material.minimumStock,
      unit: material.unit,
      quantity: parseFloat(formData.quantity),
      unitCost,
      totalCost,
      supplierId: formData.supplierId,
      supplier: selectedSupplier,
      priority: formData.priority,
      notes: formData.notes,
      isAutoGenerated: false
    });
    
    setIsSubmitting(false);
    onClose();
  };
  
  return (
    <div className="modal-overlay" onClick={(e) => e.target === e.currentTarget && onClose()}>
      <div className="modal" style={{ maxWidth: '500px' }}>
        <div className="modal-header">
          <h3 className="modal-title">
            <Plus size={18} style={{ display: 'inline', marginRight: '8px' }} />
            Create Purchase Requisition
          </h3>
          <button className="modal-close" onClick={onClose}>
            <X size={20} />
          </button>
        </div>
        
        <form onSubmit={handleSubmit}>
          <div className="modal-body">
            <div style={{ padding: '12px', backgroundColor: '#e3f2fd', borderRadius: '6px', marginBottom: '16px' }}>
              <div style={{ fontSize: '14px', fontWeight: 500 }}>
                <Package size={14} style={{ display: 'inline', marginRight: '4px' }} />
                {material?.name}
              </div>
              <div style={{ fontSize: '12px', color: '#6b7280', marginTop: '4px' }}>
                Code: {material?.code} • Current: {material?.quantity?.toLocaleString()} {material?.unit}
              </div>
            </div>
            
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
              <div className="form-group">
                <label className="form-label">Quantity ({material?.unit}) *</label>
                <input
                  type="number"
                  className="form-input"
                  value={formData.quantity}
                  onChange={(e) => setFormData({ ...formData, quantity: e.target.value })}
                  min="1"
                  step="1"
                  required
                />
              </div>
              
              <div className="form-group">
                <label className="form-label">Priority</label>
                <select
                  className="form-select"
                  value={formData.priority}
                  onChange={(e) => setFormData({ ...formData, priority: e.target.value })}
                >
                  <option value="low">Low</option>
                  <option value="medium">Medium</option>
                  <option value="high">High</option>
                </select>
              </div>
            </div>
            
            <div className="form-group">
              <label className="form-label">Unit Cost (EGP)</label>
              <input
                type="number"
                className="form-input"
                value={unitCost}
                readOnly
                style={{ backgroundColor: '#f3f4f6' }}
              />
            </div>
            
            <div style={{ 
              padding: '12px', 
              backgroundColor: '#f9fafb', 
              borderRadius: '6px',
              marginBottom: '16px'
            }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontWeight: 'bold', fontSize: '16px', color: '#22c55e' }}>
                <span>Estimated Total:</span>
                <span>EGP {totalCost.toLocaleString()}</span>
              </div>
            </div>
            
            <div className="form-group">
              <label className="form-label">Suggested Suppliers</label>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
                {suppliers
                  .filter(s => s.materials?.includes(material?.name))
                  .map(supplier => (
                    <label key={supplier._id} style={{
                      display: 'flex',
                      alignItems: 'center',
                      gap: '8px',
                      padding: '8px',
                      borderRadius: '6px',
                      border: formData.supplierId === supplier._id ? '2px solid #3b82f6' : '1px solid #e5e7eb',
                      cursor: 'pointer',
                      backgroundColor: formData.supplierId === supplier._id ? '#eff6ff' : 'white'
                    }}>
                      <input
                        type="radio"
                        name="supplier"
                        value={supplier._id}
                        checked={formData.supplierId === supplier._id}
                        onChange={(e) => setFormData({ ...formData, supplierId: e.target.value })}
                      />
                      <div style={{ flex: 1 }}>
                        <div style={{ fontWeight: 500 }}>{supplier.name}</div>
                        <div style={{ fontSize: '12px', color: '#6b7280' }}>
                          Rating: {supplier.rating} • On-time: {supplier.onTimeDelivery}%
                        </div>
                      </div>
                    </label>
                  ))}
                {suppliers.filter(s => s.materials?.includes(material?.name)).length === 0 && (
                  <div style={{ color: '#9ca3af', fontStyle: 'italic', fontSize: '14px' }}>
                    No suppliers linked to this material. Please add suppliers first.
                  </div>
                )}
              </div>
            </div>
            
            <div className="form-group">
              <label className="form-label">Notes</label>
              <textarea
                className="form-textarea"
                value={formData.notes}
                onChange={(e) => setFormData({ ...formData, notes: e.target.value })}
                placeholder="Additional requirements or notes..."
                rows="3"
              />
            </div>
          </div>
          
          <div className="modal-footer">
            <button type="button" className="btn btn-secondary" onClick={onClose}>
              Cancel
            </button>
            <button 
              type="submit" 
              className="btn btn-success"
              disabled={isSubmitting || !formData.supplierId}
            >
              {isSubmitting ? (
                <>
                  <RefreshCw size={16} style={{ animation: 'spin 1s linear infinite', marginRight: '8px', display: 'inline' }} />
                  Creating...
                </>
              ) : (
                <>
                  <FileText size={16} style={{ marginRight: '8px', display: 'inline' }} />
                  Create PR
                </>
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

// Main AutoPO Component
const AutoPO = () => {
  const [activeTab, setActiveTab] = useState('dashboard');
  const [rawMaterials, setRawMaterials] = useState([]);
  const [suppliers, setSuppliers] = useState([]);
  const [purchaseRequisitions, setPurchaseRequisitions] = useState([]);
  const [purchaseOrders, setPurchaseOrders] = useState([]);
  const [notifications, setNotifications] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showSettingsModal, setShowSettingsModal] = useState(false);
  const [showCreatePRModal, setShowCreatePRModal] = useState(false);
  const [selectedMaterial, setSelectedMaterial] = useState(null);
  const [notification, setNotification] = useState(null);
  
  // Fetch data
  const fetchData = useCallback(async () => {
    setLoading(true);
    try {
      const [materialsRes, suppliersRes, prsRes, posRes, notificationsRes] = await Promise.all([
        fetch(`${API_URL}/inventory/raw-materials`, { headers: headers() }),
        fetch(`${API_URL}/suppliers`, { headers: headers() }),
        fetch(`${API_URL}/purchase-requisitions`, { headers: headers() }),
        fetch(`${API_URL}/purchase-orders`, { headers: headers() }),
        fetch(`${API_URL}/notifications?type=auto_po`, { headers: headers() })
      ]);
      
      if (materialsRes.ok) {
        const data = await materialsRes.json();
        const materials = data.materials || data || [];
        setRawMaterials(materials.length > 0 ? materials : demoRawMaterials);
      } else {
        setRawMaterials(demoRawMaterials);
      }
      
      if (suppliersRes.ok) {
        const data = await suppliersRes.json();
        setSuppliers(data.data || data || demoSuppliers);
      } else {
        setSuppliers(demoSuppliers);
      }
      
      if (prsRes.ok) {
        const data = await prsRes.json();
        setPurchaseRequisitions(data.data || data || demoPurchaseRequisitions);
      } else {
        setPurchaseRequisitions(demoPurchaseRequisitions);
      }
      
      if (posRes.ok) {
        const data = await posRes.json();
        setPurchaseOrders(data.data || data || demoPurchaseOrders);
      } else {
        setPurchaseOrders(demoPurchaseOrders);
      }
      
      if (notificationsRes.ok) {
        const data = await notificationsRes.json();
        setNotifications(data.data || data || demoNotifications);
      } else {
        setNotifications(demoNotifications);
      }
    } catch (error) {
      console.error('Error fetching data:', error);
      setRawMaterials(demoRawMaterials);
      setSuppliers(demoSuppliers);
      setPurchaseRequisitions(demoPurchaseRequisitions);
      setPurchaseOrders(demoPurchaseOrders);
      setNotifications(demoNotifications);
    } finally {
      setLoading(false);
    }
  }, []);
  
  useEffect(() => {
    fetchData();
  }, [fetchData]);
  
  // Check for low stock and generate PRs
  useEffect(() => {
    const checkLowStock = async () => {
      const lowStockMaterials = rawMaterials.filter(m => 
        m.autoPOEnabled && 
        m.quantity <= m.reorderLevel &&
        !purchaseRequisitions.some(pr => 
          pr.material._id === m._id && 
          (pr.status === 'pending' || pr.status === 'pending_approval')
        )
      );
      
      for (const material of lowStockMaterials) {
        await generateAutoPR(material);
      }
    };
    
    if (rawMaterials.length > 0) {
      checkLowStock();
    }
  }, [rawMaterials]);
  
  // Generate auto PR
  const generateAutoPR = async (material) => {
    try {
      // Find suppliers for this material
      const materialSuppliers = suppliers.filter(s => 
        s.materials?.includes(material.name)
      );
      
      const preferredSupplier = material.preferredSupplier 
        ? suppliers.find(s => s._id === material.preferredSupplier || s.name === material.preferredSupplier)
        : materialSuppliers[0];
      
      const prData = {
        materialId: material._id,
        materialName: material.name,
        materialCode: material.code,
        currentStock: material.quantity,
        minimumStock: material.minimumStock,
        unit: material.unit,
        quantity: material.reorderQuantity || material.minimumStock * 2,
        unitCost: material.costPerUnit,
        totalCost: (material.reorderQuantity || material.minimumStock * 2) * material.costPerUnit,
        supplierId: preferredSupplier?._id,
        supplier: preferredSupplier,
        suggestedSuppliers: materialSuppliers.map(s => s.name),
        priority: material.quantity <= material.minimumStock * 0.5 ? 'high' : 'medium',
        notes: 'Auto-generated: Stock below reorder level',
        isAutoGenerated: true
      };
      
      // Create PR via API
      const response = await fetch(`${API_URL}/purchase-requisitions`, {
        method: 'POST',
        headers: headers(),
        body: JSON.stringify(prData)
      });
      
      if (response.ok) {
        const created = await response.json();
        setPurchaseRequisitions(prev => [created, ...prev]);
        showNotification(`Auto-generated PR for ${material.name}`, 'info');
      } else {
        // Fallback: Create locally
        const newPR = {
          _id: `pr-${Date.now()}`,
          prNumber: `PR-${new Date().getFullYear()}-${String(purchaseRequisitions.length + 1).padStart(3, '0')}`,
          material: {
            _id: material._id,
            name: material.name,
            code: material.code,
            currentStock: material.quantity,
            minimumStock: material.minimumStock,
            unit: material.unit
          },
          ...prData,
          status: 'pending',
          createdAt: new Date().toISOString(),
          createdBy: 'System'
        };
        setPurchaseRequisitions(prev => [newPR, ...prev]);
        showNotification(`Auto-generated PR for ${material.name} (offline)`, 'info');
      }
    } catch (error) {
      console.error('Error generating auto PR:', error);
    }
  };
  
  // Show notification
  const showNotification = (message, type = 'success') => {
    setNotification({ message, type });
    setTimeout(() => setNotification(null), 5000);
  };
  
  // Get low stock materials
  const lowStockMaterials = rawMaterials.filter(m => 
    m.quantity <= m.minimumStock
  );
  
  // Get pending PRs
  const pendingPRs = purchaseRequisitions.filter(pr => 
    pr.status === 'pending' || pr.status === 'pending_approval'
  );
  
  // Handle approve PR
  const handleApprovePR = async (prData) => {
    try {
      // Create PO
      const poPayload = {
        prId: prData._id,
        prNumber: prData.prNumber,
        supplierId: prData.supplierId,
        items: [{
          material: prData.materialName,
          quantity: prData.quantity,
          unit: prData.material.unit,
          unitPrice: prData.unitCost,
          total: prData.quantity * prData.unitCost
        }],
        subtotal: prData.quantity * prData.unitCost,
        vat: prData.quantity * prData.unitCost * 0.14,
        total: prData.quantity * prData.unitCost * 1.14,
        deliveryDate: prData.deliveryDate,
        notes: prData.notes,
        status: 'approved'
      };
      
      const poResponse = await fetch(`${API_URL}/purchase-orders`, {
        method: 'POST',
        headers: headers(),
        body: JSON.stringify(poPayload)
      });
      
      if (poResponse.ok) {
        const createdPO = await poResponse.json();
        
        // Update PR status
        await fetch(`${API_URL}/purchase-requisitions/${prData._id}/approve`, {
          method: 'PUT',
          headers: headers(),
          body: JSON.stringify({ poId: createdPO._id })
        });
        
        // Create inventory entry
        await fetch(`${API_URL}/inventory/orders`, {
          method: 'POST',
          headers: headers(),
          body: JSON.stringify({
            materialId: prData.materialId,
            quantity: prData.quantity,
            purchaseOrderId: createdPO._id,
            status: 'on_order'
          })
        });
        
        // Create payable
        await fetch(`${API_URL}/payables`, {
          method: 'POST',
          headers: headers(),
          body: JSON.stringify({
            supplierId: prData.supplierId,
            purchaseOrderId: createdPO._id,
            amount: poPayload.total,
            description: `PO ${createdPO.poNumber} - ${prData.materialName}`,
            dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0]
          })
        });
        
        // Send WhatsApp notification
        if (prData.supplier?.whatsapp) {
          const message = `Purchase Order Approved\n\nPO: ${createdPO.poNumber}\nMaterial: ${prData.materialName}\nQuantity: ${prData.quantity} ${prData.material.unit}\nTotal: EGP ${poPayload.total.toLocaleString()}\nDelivery: ${prData.deliveryDate}`;
          const url = `https://wa.me/${prData.supplier.whatsapp.replace(/\D/g, '')}?text=${encodeURIComponent(message)}`;
          window.open(url, '_blank');
        }
        
        setPurchaseOrders(prev => [createdPO, ...prev]);
        setPurchaseRequisitions(prev => 
          prev.map(pr => pr._id === prData._id ? { ...pr, status: 'approved' } : pr)
        );
        
        showNotification('Purchase Order created and approved successfully');
      } else {
        showNotification('PO created (offline mode)', 'info');
      }
    } catch (error) {
      console.error('Error approving PR:', error);
      showNotification('PO created (offline mode)', 'info');
    }
  };
  
  // Handle reject PR
  const handleRejectPR = async (pr) => {
    const reason = prompt('Enter rejection reason:');
    if (!reason) return;
    
    try {
      const response = await fetch(`${API_URL}/purchase-requisitions/${pr._id}/reject`, {
        method: 'PUT',
        headers: headers(),
        body: JSON.stringify({ reason })
      });
      
      if (response.ok) {
        setPurchaseRequisitions(prev => 
          prev.map(p => p._id === pr._id ? { ...p, status: 'rejected', rejectionReason: reason } : p)
        );
        showNotification('PR rejected');
      } else {
        setPurchaseRequisitions(prev => 
          prev.map(p => p._id === pr._id ? { ...p, status: 'rejected', rejectionReason: reason } : p)
        );
        showNotification('PR rejected (offline)');
      }
    } catch (error) {
      console.error('Error rejecting PR:', error);
    }
  };
  
  // Handle create manual PR
  const handleCreatePR = async (prData) => {
    try {
      const response = await fetch(`${API_URL}/purchase-requisitions`, {
        method: 'POST',
        headers: headers(),
        body: JSON.stringify(prData)
      });
      
      if (response.ok) {
        const created = await response.json();
        setPurchaseRequisitions(prev => [created, ...prev]);
        showNotification('Purchase Requisition created successfully');
      } else {
        const newPR = {
          _id: `pr-${Date.now()}`,
          prNumber: `PR-${new Date().getFullYear()}-${String(purchaseRequisitions.length + 1).padStart(3, '0')}`,
          material: {
            _id: prData.materialId,
            name: prData.materialName,
            code: prData.materialCode,
            currentStock: prData.currentStock,
            minimumStock: prData.minimumStock,
            unit: prData.unit
          },
          ...prData,
          status: 'pending',
          createdAt: new Date().toISOString(),
          createdBy: 'Manual'
        };
        setPurchaseRequisitions(prev => [newPR, ...prev]);
        showNotification('PR created (offline mode)');
      }
    } catch (error) {
      console.error('Error creating PR:', error);
    }
  };
  
  // Handle save material settings
  const handleSaveMaterialSettings = async (materialData) => {
    try {
      const response = await fetch(`${API_URL}/inventory/raw-materials/${materialData._id}/settings`, {
        method: 'PUT',
        headers: headers(),
        body: JSON.stringify({
          autoPOEnabled: materialData.autoPOEnabled,
          minimumStock: materialData.minimumStock,
          reorderLevel: materialData.reorderLevel,
          reorderQuantity: materialData.reorderQuantity,
          preferredSupplier: materialData.preferredSupplier
        })
      });
      
      if (response.ok) {
        setRawMaterials(prev => 
          prev.map(m => m._id === materialData._id ? materialData : m)
        );
        showNotification('Settings saved successfully');
      } else {
        setRawMaterials(prev => 
          prev.map(m => m._id === materialData._id ? materialData : m)
        );
        showNotification('Settings saved (offline mode)');
      }
    } catch (error) {
      console.error('Error saving settings:', error);
    }
  };
  
  return (
    <div className="page-container">
      {/* Notification */}
      {notification && (
        <div
          className="notification-toast"
          style={{
            position: 'fixed',
            top: '20px',
            right: '20px',
            padding: '16px 24px',
            borderRadius: '8px',
            backgroundColor: notification.type === 'error' ? '#fee2e2' : notification.type === 'info' ? '#dbeafe' : '#dcfce7',
            color: notification.type === 'error' ? '#991b1b' : notification.type === 'info' ? '#1e40af' : '#166534',
            boxShadow: '0 4px 6px rgba(0,0,0,0.1)',
            zIndex: 9999,
            display: 'flex',
            alignItems: 'center',
            gap: '8px',
            maxWidth: '400px',
            wordBreak: 'break-word'
          }}
        >
          {notification.type === 'error' ? <AlertCircle size={20} /> : notification.type === 'info' ? <Info size={20} /> : <Check size={20} />}
          {notification.message}
        </div>
      )}
      
      {/* Page Header */}
      <div className="page-header flex-col">
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div>
            <h1 style={{ margin: 0, display: 'flex', alignItems: 'center', gap: '12px' }}>
              <Bell size={28} style={{ color: '#3b82f6' }} />
              Auto Purchase Order System
            </h1>
            <p style={{ margin: '4px 0 0 0', color: '#6b7280' }}>
              Automated stock monitoring, requisition generation, and approval workflow
            </p>
          </div>
          <div style={{ display: 'flex', gap: '8px' }}>
            <button 
              className="btn btn-secondary"
              onClick={() => setActiveTab('settings')}
            >
              <Settings size={16} style={{ marginRight: '4px', display: 'inline' }} />
              Settings
            </button>
            <button 
              className="btn btn-primary"
              onClick={fetchData}
            >
              <RefreshCw size={16} style={{ marginRight: '4px', display: 'inline' }} />
              Refresh
            </button>
          </div>
        </div>
        
        {/* Stats Cards */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: '16px' }}>
          <div style={{ padding: '16px', backgroundColor: '#fef3c7', borderRadius: '8px', border: '1px solid #fed7aa' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' }}>
              <AlertTriangle size={20} color="#f59e0b" />
              <span style={{ fontSize: '12px', color: '#92400e', fontWeight: 600 }}>Low Stock Alerts</span>
            </div>
            <div style={{ fontSize: '28px', fontWeight: 'bold', color: '#f59e0b' }}>
              {lowStockMaterials.length}
            </div>
            <div style={{ fontSize: '12px', color: '#92400e' }}>Materials need attention</div>
          </div>
          
          <div style={{ padding: '16px', backgroundColor: '#dbeafe', borderRadius: '8px', border: '1px solid #bfdbfe' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' }}>
              <FileText size={20} color="#3b82f6" />
              <span style={{ fontSize: '12px', color: '#1e40af', fontWeight: 600 }}>Pending PRs</span>
            </div>
            <div style={{ fontSize: '28px', fontWeight: 'bold', color: '#3b82f6' }}>
              {pendingPRs.length}
            </div>
            <div style={{ fontSize: '12px', color: '#1e40af' }}>Awaiting approval</div>
          </div>
          
          <div style={{ padding: '16px', backgroundColor: '#dcfce7', borderRadius: '8px', border: '1px solid #bbf7d0' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' }}>
              <CheckCircle2 size={20} color="#10b981" />
              <span style={{ fontSize: '12px', color: '#166534', fontWeight: 600 }}>Approved POs</span>
            </div>
            <div style={{ fontSize: '28px', fontWeight: 'bold', color: '#10b981' }}>
              {purchaseOrders.filter(po => po.status === 'approved').length}
            </div>
            <div style={{ fontSize: '12px', color: '#166534' }}>Ready to order</div>
          </div>
          
          <div style={{ padding: '16px', backgroundColor: '#f3e8ff', borderRadius: '8px', border: '1px solid #ddd6fe' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' }}>
              <Shield size={20} color="#8b5cf6" />
              <span style={{ fontSize: '12px', color: '#5b21b6', fontWeight: 600 }}>Auto-PO Enabled</span>
            </div>
            <div style={{ fontSize: '28px', fontWeight: 'bold', color: '#8b5cf6' }}>
              {rawMaterials.filter(m => m.autoPOEnabled).length}
            </div>
            <div style={{ fontSize: '12px', color: '#5b21b6' }}>Materials monitored</div>
          </div>
        </div>
      </div>
      
      {/* Navigation Tabs */}
      <div style={{ 
        display: 'flex', 
        gap: '4px', 
        borderBottom: '2px solid #e5e7eb',
        marginBottom: '24px'
      }}>
        {[
          { id: 'dashboard', label: 'Dashboard', icon: BarChart3 },
          { id: 'alerts', label: `Low Stock Alerts (${lowStockMaterials.length})`, icon: AlertTriangle },
          { id: 'requisitions', label: `PRs (${pendingPRs.length})`, icon: FileText },
          { id: 'orders', label: 'Purchase Orders', icon: Truck },
          { id: 'settings', label: 'Auto-PO Settings', icon: Settings }
        ].map(tab => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            style={{
              padding: '12px 20px',
              border: 'none',
              backgroundColor: 'transparent',
              color: activeTab === tab.id ? '#3b82f6' : '#6b7280',
              fontWeight: activeTab === tab.id ? 600 : 500,
              borderBottom: activeTab === tab.id ? '2px solid #3b82f6' : '2px solid transparent',
              marginBottom: '-2px',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '8px'
            }}
          >
            <tab.icon size={16} />
            {tab.label}
          </button>
        ))}
      </div>
      
      {/* Tab Content */}
      {loading ? (
        <div style={{ textAlign: 'center', padding: '60px' }}>
          <RefreshCw size={48} style={{ animation: 'spin 1s linear infinite', color: '#6b7280' }} />
          <p style={{ marginTop: '16px', color: '#6b7280' }}>Loading Auto-PO data...</p>
        </div>
      ) : (
        <>
          {/* Dashboard Tab */}
          {activeTab === 'dashboard' && (
            <div>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '24px' }}>
                {/* Recent Alerts */}
                <div>
                  <h3 style={{ marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                    <AlertTriangle size={20} style={{ color: '#f59e0b' }} />
                    Recent Low Stock Alerts
                  </h3>
                  {lowStockMaterials.slice(0, 3).map(material => (
                    <LowStockAlertCard
                      key={material._id}
                      material={material}
                      onCreatePR={(mat) => { setSelectedMaterial(mat); setShowCreatePRModal(true); }}
                      onViewMaterial={(mat) => { setSelectedMaterial(mat); setShowSettingsModal(true); }}
                    />
                  ))}
                  {lowStockMaterials.length === 0 && (
                    <div style={{ 
                      padding: '24px', 
                      textAlign: 'center', 
                      backgroundColor: '#f9fafb',
                      borderRadius: '8px'
                    }}>
                      <CheckCircle2 size={32} style={{ color: '#22c55e', marginBottom: '8px' }} />
                      <p style={{ color: '#6b7280' }}>No low stock alerts</p>
                    </div>
                  )}
                  {lowStockMaterials.length > 3 && (
                    <button 
                      className="btn btn-secondary" 
                      style={{ width: '100%', marginTop: '8px' }}
                      onClick={() => setActiveTab('alerts')}
                    >
                      View All {lowStockMaterials.length} Alerts
                    </button>
                  )}
                </div>
                
                {/* Pending PRs */}
                <div>
                  <h3 style={{ marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                    <FileText size={20} style={{ color: '#3b82f6' }} />
                    Pending Requisitions
                  </h3>
                  {pendingPRs.slice(0, 3).map(pr => (
                    <PurchaseRequisitionCard
                      key={pr._id}
                      pr={pr}
                      suppliers={suppliers}
                      onApprove={handleApprovePR}
                      onReject={handleRejectPR}
                      onView={(p) => console.log('View PR:', p)}
                    />
                  ))}
                  {pendingPRs.length === 0 && (
                    <div style={{ 
                      padding: '24px', 
                      textAlign: 'center', 
                      backgroundColor: '#f9fafb',
                      borderRadius: '8px'
                    }}>
                      <CheckCircle2 size={32} style={{ color: '#22c55e', marginBottom: '8px' }} />
                      <p style={{ color: '#6b7280' }}>No pending requisitions</p>
                    </div>
                  )}
                  {pendingPRs.length > 3 && (
                    <button 
                      className="btn btn-secondary" 
                      style={{ width: '100%', marginTop: '8px' }}
                      onClick={() => setActiveTab('requisitions')}
                    >
                      View All {pendingPRs.length} PRs
                    </button>
                  )}
                </div>
              </div>
              
              {/* Recent Purchase Orders */}
              <div style={{ marginTop: '32px' }}>
                <h3 style={{ marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <Truck size={20} style={{ color: '#22c55e' }} />
                  Recent Purchase Orders
                </h3>
                <div className="table-container">
                  <table className="table">
                    <thead>
                      <tr>
                        <th>PO Number</th>
                        <th>Supplier</th>
                        <th>Material</th>
                        <th>Quantity</th>
                        <th>Total</th>
                        <th>Delivery</th>
                        <th>Status</th>
                      </tr>
                    </thead>
                    <tbody>
                      {purchaseOrders.slice(0, 5).map(po => (
                        <tr key={po._id}>
                          <td>
                            <div style={{ fontWeight: 500 }}>{po.poNumber}</div>
                            <div style={{ fontSize: '12px', color: '#6b7280' }}>PR: {po.prNumber}</div>
                          </td>
                          <td>{po.supplier.name}</td>
                          <td>{po.items[0]?.material}</td>
                          <td>{po.items[0]?.quantity?.toLocaleString()} {po.items[0]?.unit}</td>
                          <td style={{ fontWeight: 600, color: '#22c55e' }}>
                            EGP {po.total?.toLocaleString()}
                          </td>
                          <td>{new Date(po.deliveryDate).toLocaleDateString()}</td>
                          <td>
                            <StatusBadge status={po.status} type="po" />
                          </td>
                        </tr>
                      ))}
                      {purchaseOrders.length === 0 && (
                        <tr>
                          <td colSpan="7" style={{ textAlign: 'center', padding: '24px', color: '#6b7280' }}>
                            No purchase orders yet
                          </td>
                        </tr>
                      )}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          )}
          
          {/* Low Stock Alerts Tab */}
          {activeTab === 'alerts' && (
            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
                <h3>Low Stock Materials</h3>
                <span style={{ color: '#6b7280' }}>
                  {lowStockMaterials.length} materials below minimum stock level
                </span>
              </div>
              
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(350px, 1fr))', gap: '16px' }}>
                {lowStockMaterials.map(material => (
                  <LowStockAlertCard
                    key={material._id}
                    material={material}
                    onCreatePR={(mat) => { setSelectedMaterial(mat); setShowCreatePRModal(true); }}
                    onViewMaterial={(mat) => { setSelectedMaterial(mat); setShowSettingsModal(true); }}
                  />
                ))}
              </div>
              
              {lowStockMaterials.length === 0 && (
                <div style={{ 
                  padding: '60px', 
                  textAlign: 'center', 
                  backgroundColor: '#f9fafb',
                  borderRadius: '8px'
                }}>
                  <CheckCircle2 size={48} style={{ color: '#22c55e', marginBottom: '16px' }} />
                  <h3 style={{ margin: '0 0 8px 0' }}>All Stock Levels Normal</h3>
                  <p style={{ color: '#6b7280', margin: 0 }}>
                    All materials are above their minimum stock thresholds.
                  </p>
                </div>
              )}
            </div>
          )}
          
          {/* Purchase Requisitions Tab */}
          {activeTab === 'requisitions' && (
            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
                <h3>Purchase Requisitions</h3>
                <div style={{ display: 'flex', gap: '8px' }}>
                  <select className="form-select" style={{ width: '150px' }}>
                    <option value="all">All Status</option>
                    <option value="pending">Pending</option>
                    <option value="approved">Approved</option>
                    <option value="rejected">Rejected</option>
                  </select>
                </div>
              </div>
              
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(400px, 1fr))', gap: '16px' }}>
                {purchaseRequisitions.map(pr => (
                  <PurchaseRequisitionCard
                    key={pr._id}
                    pr={pr}
                    suppliers={suppliers}
                    onApprove={handleApprovePR}
                    onReject={handleRejectPR}
                    onView={(p) => console.log('View PR:', p)}
                  />
                ))}
              </div>
              
              {purchaseRequisitions.length === 0 && (
                <div style={{ 
                  padding: '60px', 
                  textAlign: 'center', 
                  backgroundColor: '#f9fafb',
                  borderRadius: '8px'
                }}>
                  <FileText size={48} style={{ color: '#d1d5db', marginBottom: '16px' }} />
                  <h3 style={{ margin: '0 0 8px 0' }}>No Purchase Requisitions</h3>
                  <p style={{ color: '#6b7280', margin: '0 0 16px 0' }}>
                    PRs will be created automatically when stock falls below minimum levels.
                  </p>
                </div>
              )}
            </div>
          )}
          
          {/* Purchase Orders Tab */}
          {activeTab === 'orders' && (
            <div>
              <div className="table-container">
                <table className="table">
                  <thead>
                    <tr>
                      <th>PO Number</th>
                      <th>PR Reference</th>
                      <th>Supplier</th>
                      <th>Items</th>
                      <th>Total (EGP)</th>
                      <th>Delivery Date</th>
                      <th>Status</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    {purchaseOrders.map(po => (
                      <tr key={po._id}>
                        <td>
                          <div style={{ fontWeight: 500 }}>{po.poNumber}</div>
                          <div style={{ fontSize: '12px', color: '#6b7280' }}>
                            {new Date(po.createdAt).toLocaleDateString()}
                          </div>
                        </td>
                        <td>{po.prNumber}</td>
                        <td>
                          <div>{po.supplier.name}</div>
                          <div style={{ fontSize: '12px', color: '#6b7280' }}>
                            {po.supplier.whatsapp}
                          </div>
                        </td>
                        <td>
                          {po.items.map((item, idx) => (
                            <div key={idx} style={{ fontSize: '13px' }}>
                              {item.quantity} {item.unit} {item.material}
                            </div>
                          ))}
                        </td>
                        <td style={{ fontWeight: 600 }}>
                          {po.total?.toLocaleString()}
                        </td>
                        <td>{new Date(po.deliveryDate).toLocaleDateString()}</td>
                        <td>
                          <StatusBadge status={po.status} type="po" />
                        </td>
                        <td>
                          <div style={{ display: 'flex', gap: '4px' }}>
                            {po.status === 'approved' && (
                              <button 
                                className="btn btn-sm"
                                style={{ backgroundColor: '#25D366', color: 'white', border: 'none' }}
                                onClick={() => {
                                  const message = `Purchase Order: ${po.poNumber}\nTotal: EGP ${po.total.toLocaleString()}\nDelivery: ${po.deliveryDate}`;
                                  const url = `https://wa.me/${po.supplier.whatsapp.replace(/\D/g, '')}?text=${encodeURIComponent(message)}`;
                                  window.open(url, '_blank');
                                }}
                              >
                                <WhatsApp size={14} />
                              </button>
                            )}
                            <button className="btn btn-sm">
                              <Eye size={14} />
                            </button>
                            <button className="btn btn-sm">
                              <Printer size={14} />
                            </button>
                          </div>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}
          
          {/* Settings Tab */}
          {activeTab === 'settings' && (
            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
                <div>
                  <h3>Auto-PO Configuration</h3>
                  <p style={{ color: '#6b7280', margin: '4px 0 0 0' }}>
                    Configure automatic purchase order settings for each material
                  </p>
                </div>
              </div>
              
              <div className="table-container">
                <table className="table">
                  <thead>
                    <tr>
                      <th>Material</th>
                      <th>Auto-PO</th>
                      <th>Current Stock</th>
                      <th>Min. Stock</th>
                      <th>Reorder Level</th>
                      <th>Reorder Qty</th>
                      <th>Preferred Supplier</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    {rawMaterials.map(material => {
                      const isLowStock = material.quantity <= material.minimumStock;
                      const preferredSupplier = suppliers.find(s => 
                        s._id === material.preferredSupplier || s.name === material.preferredSupplier
                      );
                      
                      return (
                        <tr key={material._id} style={{ backgroundColor: isLowStock ? '#fef3c7' : 'white' }}>
                          <td>
                            <div style={{ fontWeight: 500 }}>{material.name}</div>
                            <div style={{ fontSize: '12px', color: '#6b7280' }}>{material.code}</div>
                            {isLowStock && (
                              <span style={{ 
                                fontSize: '11px', 
                                color: '#f59e0b',
                                display: 'flex',
                                alignItems: 'center',
                                gap: '4px',
                                marginTop: '4px'
                              }}>
                                <AlertTriangle size={10} />
                                Low Stock
                              </span>
                            )}
                          </td>
                          <td>
                            <span style={{
                              padding: '4px 8px',
                              borderRadius: '12px',
                              fontSize: '12px',
                              fontWeight: '500',
                              backgroundColor: material.autoPOEnabled ? '#dcfce7' : '#f3f4f6',
                              color: material.autoPOEnabled ? '#166534' : '#6b7280'
                            }}>
                              {material.autoPOEnabled ? 'Enabled' : 'Disabled'}
                            </span>
                          </td>
                          <td>
                            <span style={{ 
                              fontWeight: 600,
                              color: isLowStock ? '#dc2626' : '#22c55e'
                            }}>
                              {material.quantity.toLocaleString()} {material.unit}
                            </span>
                          </td>
                          <td>{material.minimumStock.toLocaleString()} {material.unit}</td>
                          <td>{material.reorderLevel?.toLocaleString() || material.minimumStock} {material.unit}</td>
                          <td>{material.reorderQuantity?.toLocaleString() || '-'} {material.unit}</td>
                          <td>
                            {preferredSupplier ? (
                              <span style={{ 
                                padding: '4px 8px',
                                borderRadius: '4px',
                                fontSize: '12px',
                                backgroundColor: '#e3f2fd',
                                color: '#1976d2'
                              }}>
                                {preferredSupplier.name}
                              </span>
                            ) : (
                              <span style={{ color: '#9ca3af', fontStyle: 'italic' }}>None</span>
                            )}
                          </td>
                          <td>
                            <button 
                              className="btn btn-sm btn-primary"
                              onClick={() => { setSelectedMaterial(material); setShowSettingsModal(true); }}
                            >
                              <Settings size={14} style={{ marginRight: '4px', display: 'inline' }} />
                              Configure
                            </button>
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </>
      )}
      
      {/* Modals */}
      {showSettingsModal && selectedMaterial && (
        <MaterialSettingsModal
          material={selectedMaterial}
          suppliers={suppliers}
          onClose={() => { setShowSettingsModal(false); setSelectedMaterial(null); }}
          onSave={handleSaveMaterialSettings}
        />
      )}
      
      {showCreatePRModal && selectedMaterial && (
        <CreatePRModal
          material={selectedMaterial}
          suppliers={suppliers}
          onClose={() => { setShowCreatePRModal(false); setSelectedMaterial(null); }}
          onSubmit={handleCreatePR}
        />
      )}
    </div>
  );
};

export default AutoPO;